server:
  port: 8085

spring:
  application:
    name: nemesis-activity



#eureka
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8787/eureka/  #注册中心地址
#开启断路器
feign.hystrix.enabled: true


