server:
  port: 8787



spring:
  application:
    name: nemesis-center

eureka:
  server:
    # 关闭自我保护机制 开发的时候可以开启 保证不可用的服务能够及时剔除
    enable-self-preservation: false
    #服务器定时清理列表(毫秒)
    eviction-interval-timer-in-ms: 1000
  instance:
    hostname: localhost
    #配置服务超时时间(此值将设置为至少高于leaseRenewalIntervalInSeconds中指定的值。)
    lease-expiration-duration-in-seconds: 10
  client:
    #是否要注册到其他Server上
    registerWithEureka: false
    #是否需要拉取服务信息。和是否注册一样
    fetchRegistry: false
    serviceUrl:
      #Eureka服务地址
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

logging:
  level:
    com.netflix: warn
