#mouse
server:
  port: 8087

#开启断路器
feign.hystrix.enabled: true

mybatis-plus:
  configuration:
    default-fetch-size: 100
    default-statement-timeout: 30
  mapper-locations: classpath*:**/mapper/*Mapper.xml #mapper扫描
  type-aliases-package: com.lsjyy.nemesis.mouse.pojo


logging:
    level:
        root: INFO
        org.springframework: INFO
        com.lsjyy.nemesis.mouse: DEBUG
        com.baomidou.mybatisplus: INFO