server:
  port: 8087

spring:
  application:
    name: nemesis-mouse
  redis:
    host: 118.89.238.168
    port: 3824
    password: 2927213lsjyy
  rabbitmq:
    port: 5672
    username: guest
    password: guest
    host: localhost
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      url: jdbc:mysql://118.89.238.168/nemesis?useSSL=false&characterEncoding=utf-8
      username: lsjyy
      password: 2927213lsj
      initialSize: 5  # 初始连接数
      minIdle: 10  # 最小空闲连接
      maxActive: 20 # 最大活跃数量
      maxWait: 60000 # 配置获取连接等待超时的时间
      timeBetweenEvictionRunsMillis: 60000  # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      minEvictableIdleTimeMillis: 300000   # 配置一个连接在池中最小生存的时间，单位是毫秒
      maxEvictableIdleTimeMillis: 900000 # 配置一个连接在池中最大生存的时间，单位是毫秒
      validationQuery: SELECT 1 FROM DUAL # 配置检测连接是否有效
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      webStatFilter:
          enabled: true
      statViewServlet:
          enabled: true
          allow:  # 设置白名单，不填则允许所有访问
          url-pattern: /druid/*
          login-username: admin
          login-password: admin
      filter:
          stat:
              enabled: true
              log-slow-sql: true  # 慢SQL记录
              slow-sql-millis: 1000
              merge-sql: true
          wall:
              config:
                  multi-statement-allow: true




#eureka
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8787/eureka/  #注册中心地址
#开启断路器
feign.hystrix.enabled: true

mybatis-plus:
  configuration:
    default-fetch-size: 100
    default-statement-timeout: 30
  mapper-locations: classpath*:**/mapper/*Mapper.xml #mapper扫描
  type-aliases-package: com.lsjyy.nemesis.mouse.pojo


logging:
    level:
        root: INFO
        org.springframework: INFO
        com.lsjyy.nemesis.mouse: DEBUG
        com.baomidou.mybatisplus: INFO