server:
  port: 8182

#order
spring:
  kafka:
    consumer:
      #消费组
      group-id: order-group
      #不自动提交便宜量
      enable-auto-commit: false


#开启断路器
feign.hystrix.enabled: true

mybatis-plus:
  configuration:
    default-fetch-size: 100
    default-statement-timeout: 30
  mapper-locations: classpath*:**/mapper/*Mapper.xml #mapper扫描
  type-aliases-package: com.lsjyy.nemesis.order.pojo


logging:
    level:
        root: INFO
        org.springframework: INFO
        com.lsjyy.nemesis.order: DEBUG
        com.baomidou.mybatisplus: INFO

#tx-lcn:
#  client:
#    manager-address: 127.0.0.1:8070
#  ribbon:
#    loadbalancer:
#      dtx:
#        enabled: true
