server:
  port: 8083

#cargo
spring:
  kafka:
    consumer:
      group-id: cargo-group




#mybatis 配置
mybatis-plus:
  configuration:
    default-fetch-size: 100
    default-statement-timeout: 30
  mapper-locations: classpath*:**/mapper/*Mapper.xml #mapper扫描
  type-aliases-package: com.lsjyy.nemesis.cargo.pojo

#开启断路器
feign.hystrix.enabled: true

#日志配置
logging:
    level:
        root: INFO
        org.springframework: INFO
        com.lsjyy.nemesis.cargo: DEBUG
        com.baomidou.mybatisplus: INFO
#tx-lcn:
#  client:
#    manager-address: 127.0.0.1:8070
#  ribbon:
#    loadbalancer:
#      dtx:
#        enabled: true