server:
  port: 8011

spring:
  application:
    name: nemesis-system
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://118.89.238.168/nemesis?useSSL=false&characterEncoding=utf-8
    password: 2927213lsj
    username: lsjyy
  redis:
    password: 2927213lsjyy
    lettuce:
      pool:
        max-active: 1000 #连接池最大连接数（使用负值表示没有限制）
        max-idle: 10 # 连接池中的最大空闲连接
        min-idle: 5
        max-wait: -1ms # 连接池中的最小空闲连接 # 连接池最大阻塞等待时间（使用负值表示没有限制）
    sentinel: #哨兵模式
      master: mymaster
      nodes:
        - 118.89.238.168:23824
        - 47.104.60.115:23824
        - 49.234.205.96:23824
mybatis-plus:
  configuration:
    default-fetch-size: 100
    default-statement-timeout: 30
  mapper-locations: classpath*:**/mapper/*Mapper.xml #mapper扫描
  type-aliases-package: com.lsjyy.nemesis.system.pojo


logging:
    level:
        root: INFO
        org.springframework: INFO
        com.lsjyy.nemesis.system: DEBUG
        com.baomidou.mybatisplus: INFO
eureka:
  client:
    service-url:
       defaultZone: http://localhost:8787/eureka/
#开启断路器
feign.hystrix.enabled: true

