server:
  port: 8011

spring:
  #kafka集群
  kafka:
    #kafka集群
    consumer:
      #消费组
      group-id: system-group


#mybatis-plus基本配置
mybatis-plus:
  configuration:
    default-fetch-size: 100
    default-statement-timeout: 30
  mapper-locations: classpath*:**/mapper/*Mapper.xml #mapper扫描
  type-aliases-package: com.lsjyy.nemesis.system.pojo
#日志级别
logging:
    level:
        root: INFO
        org.springframework: INFO
        com.lsjyy.nemesis.system: DEBUG
        com.baomidou.mybatisplus: INFO
#eureka
eureka:
  client:
    service-url:
       defaultZone: http://localhost:8787/eureka/

