server:
  port: 8789


spring:
  application:
    name: nemesis-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/lsjiyy/nemesis-config.git
          search-paths: resp
          username: 1206988086@qq.com
          password: 2927213lsj
          default-label: master

#eureka
eureka:
  client:
    serviceUrl:
      #注册中心地址
      defaultZone: http://49.234.205.96:8787/eureka/
     #心跳检测默认30s
    eureka-connection-idle-timeout-seconds:  5
    #从eureka服务器获取注册表信息的频率（以秒为单位）。
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true
    ip-address: 49.234.205.96
