server:
  port: 7090

spring:
  application:
    name: tx-manager
  redis:
    password: 2927213lsjyy
    lettuce:
      pool:
        max-active: 1000 #连接池最大连接数（使用负值表示没有限制）
        max-idle: 10 # 连接池中的最大空闲连接
        min-idle: 5 # 连接池中的最小空闲连接
        max-wait: -1ms  # 连接池最大阻塞等待时间（使用负值表示没有限制）
    sentinel: #哨兵模式
      master: mymaster
      nodes:
        - 118.89.238.168:23824
        - 47.104.60.115:23824
        - 49.234.205.96:23824
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://118.89.238.168/nemesis?useSSL=false&characterEncoding=utf-8
    username: lsjyy
    password: 2927213lsj
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: validate

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8787/eureka/ #注册中心地址

tx-lcn:
  #开启日志
  logger:
    enabled: true
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}
    jdbc-url: ${spring.datasource.url}
    driver-class-name: ${spring.datasource.driver-class-name}
  manager:
    #tm监听ip
    host: 127.0.0.1
    # TM监听Socket端口. 默认为 ${server.port} - 100
    port: 8070
    # 心跳检测时间(ms). 默认为 300000
    heart-time: 300000
    # 分布式事务执行总时间(ms). 默认为36000
    dtx-time: 8000
    netty:
      #参数延迟删除时间单位ms  默认为dtx-time值
      attr-delay-time: ${tx-lcn.manager.dtx-time}
    # 事务处理并发等级. 默认为机器逻辑核心数5倍
    concurrent-level: 160
    # TM后台登陆密码，默认值为codingapi
    admin-key: codingapi
    # 分布式事务锁超时时间 默认为-1，当-1时会用tx-lcn.manager.dtx-time的时间
    dtx-lock-time: ${tx-lcn.manager.dtx-time}
    # 雪花算法的sequence位长度，默认为12位.
    seq-len: 12
    ex-url-enabled: false
    # 事务异常通知（任何http协议地址。未指定协议时，为TM提供内置功能接口）。默认是邮件通知
    ex-url: /provider/email-to/***@**.com