server:
  port: 8085
  undertow:
    # 以下的配置会影响buffer,这些buffer会用于服务器连接的IO操作,有点类似netty的池化内存管理
    # 每块buffer的空间大小,越小的空间被利用越充分，不要设置太大，以免影响其他应用，合适即可
    buffer-size: 1024
    # 是否分配的直接内存(NIO直接分配的堆外内存)
    direct-buffers: true

spring:
  application:
    name: nemesis-web

#开启断路器
feign:
  hystrix:
    enabled: true


mybatis-plus:
  configuration:
    default-fetch-size: 100
    default-statement-timeout: 30
  mapper-locations: classpath*:**/mapper/*Mapper.xml #mapper扫描
  type-aliases-package: com.lsjyy.nemesis.web.pojo


logging:
    level:
        root: INFO
        org.springframework: INFO
        com.lsjyy.nemesis.web: DEBUG
        com.baomidou.mybatisplus: INFO




